### ISSUE TITLE
Create Infrastructure for embedded preferred linear solver settings

### ISSUE THREAD

**Issue by psakievich** [Exawind/nalu-wind#1077]
Our solvers currently utilize external files to set specific optimization parameters
MueLue: https://github.com/Exawind/nalu-wind/tree/master/reg_tests/xml
Hypre: https://github.com/Exawind/nalu-wind/tree/master/reg_tests/hypre_settings

The result of this is that end users are often running old outdated solver settings.

This feature request is for infrastructure to allow users to move from blocks like this:

```yaml
    # File containing hypre specific configuration options
    hypre_cfg_file: ../../hypre_settings/hypre_blade_resolved.yaml
    # YAML node used for this linear solver
    hypre_cfg_node: hypre_simple_precon

  - name: solve_elliptic
    type: hypre
    method: hypre_gmres
    preconditioner: boomerAMG
    tolerance: 1e-12
    max_iterations: 200
    kspace: 75
    output_level: 0
    write_matrix_files: no
    reuse_linear_system: yes
    recompute_preconditioner_frequency: 100
    simple_hypre_matrix_assemble: no
    dump_hypre_matrix_stats: no
    write_preassembly_matrix_files: no
```
    
to something like this:
```yaml
  - name: solve_elliptic
    solver_preset: hypre_blade_resolved
```

The infrastructure should be a map of some form so it is extendable for the different key solver scenarios we want to support.

Once this feature is implemented we will ask the solvers teams to populate some preconfigured cases that are embedded in the source code (@jhux2 @PaulMullowney). We should also preserve the old interface to allow for maximum flexibility.
