### ISSUE TITLE
Build issue on Intel introduced in PR 1325? 

### ISSUE THREAD

**Issue by ndevelder** [Exawind/nalu-wind#1335]
https://github.com/Exawind/nalu-wind/pull/1325 seems to have introduced a build issue for intel?  

# Error text

```
    307    icpc: command line warning #10121: overriding '-march=sapphirerapids' with '-xCORE-AVX512'
  >> 308    /projects/wind/ndeveld/em-exawind-flight/environments/exawind-ofdev-12182024/nalu-wind/include/ngp_utils/NgpLoopUtils.h(135): error: a value of type "unsigned int" cannot be used to 
            initialize an entity of type "const stk::mesh::Bucket *"
     309                MeshIndex meshIdx{bkt.bucket_id(), static_cast<unsigned>(bktIndex)};
     310                                  ^
     311              detected during:
     312                instantiation of "void sierra::nalu::nalu_ngp::run_entity_algorithm(const std::string &, const Mesh &, stk::topology::rank_t, const stk::mesh::Selector &, AlgFunctor) [wi
            th Mesh=stk::mesh::NgpMesh, AlgFunctor=lambda [](const MeshIndex &)->void]" at line 77 of "/projects/wind/ndeveld/em-exawind-flight/environments/exawind-ofdev-12182024/nalu-wind/incl
            ude/ngp_utils/NgpFieldBLAS.h"

```

# Compiler Spec

```
      spec: intel@=2023.2.0
      paths:
        cc: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52/compiler/2023.2.0/linux/bin/intel64/icc
        cxx: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52/compiler/2023.2.0/linux/bin/intel64/icpc
        f77: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52/compiler/2023.2.0/linux/bin/intel64/ifort
        fc: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52/compiler/2023.2.0/linux/bin/intel64/ifort
      flags: {}
      operating_system: rhel8
      target: x86_64
```
