### ISSUE TITLE
User-defined boundary condition

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#534]
Hi Nalu-Team,

Is there a way I can incorporate a user-defined boundary condition at the inlet, instead of a constant value through the .yaml files. Right now, I can only provide user-defined initial conditions from the list of Aux.C in user-functions/.

If Yes, Can a short code snippet  for the Boundary condition implementation be provided as well?

Best,
Tanmoy

**Comment by sayerhs** [comment]
You have two options: 1. write a new user function following the [one of the examples](https://github.com/Exawind/nalu-wind/blob/master/src/user_functions/WindEnergyPowerLawAuxFunction.C), or 2. use I/O transfer to read in inflow profiles from a database – see [regression test example](https://github.com/Exawind/nalu-wind/blob/master/reg_tests/test_files/ablUnstableEdge/ablUnstableEdge_rst.i). 

For the first option, create the user-function, add it to the `CMakeLists.txt`, add it as one of the possible options in `MomentumEquationSystem::register_inflow_bc` https://github.com/Exawind/nalu-wind/blob/7985704766ebbbe26b2cc13cc57ecbdeb39c2b4a/src/LowMachEquationSystem.C#L1683

recompile, and invoke that in the input file.

For the second option, you can either *dump inflow profiles* from a precursor run and reuse it, or you can [create an exodus database manually](https://github.com/Exawind/wind-utils/blob/master/src/preprocessing/InflowHistory.cpp)

**Comment by tchatte3** [comment]
Hi Shreyas,

Thanks for the quick answer. I will write a new function and add to register_inflow_bc. We are running reduced order cases, so I think option 1 is more favourable compared to 2 of running precursor. 

-Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 You might also want to add it to `initial_conditions` so that you can initialize the flowfield with the same conditions that you set at inflow when you start the simulation. 

https://github.com/Exawind/nalu-wind/blob/7985704766ebbbe26b2cc13cc57ecbdeb39c2b4a/src/LowMachEquationSystem.C#L605-L609

**Comment by tchatte3** [comment]
@sayerhs Yes, sure, you are right. Thanks very much !

**Comment by tchatte3** [comment]
@sayerhs . I was first trying out an existing fcnName in the boundary condition, e.g., the wind_energy_power_law, but could not get it to work. In the .yaml file, I was adding blocks similar to this:

```
- inflow_boundary_condition: bc_inflow
      target_name: west
      inflow_user_data:
      user_function:
        velocity: wind_energy_power_law
      user_function_parameters:
        velocity: [0, 0, 0.1428, 8.0, 0, 0, 0, 8.0]
     temperature: 300.0
     turbulent_ke: 0.095118
     specific_dissipation_rate: 2266.4

```

I tried out different versions of this, but getting either yaml parsing error or invalid nodes. I looked up in NaluParsing.C/ NaluParsing.h, but did not get much help, on what the yaml nodes should be for creating the user defined boundary condition. I know, I am incorporating invalid node names n the .yaml file, but I could not find a way to correctly implement the inflow boundary condition.

**Comment by sayerhs** [comment]
@tchatte3 YAML, like Python, is sensitive to identation. So make sure that you are using spaces/tabs consistently for indentation. In the snippet you posted above, you will notice that the `inflow_user_data` is wrongly indented. Here are some examples for `initial_conditions` and `inflow` BC

### Initial conditions

```yaml
    initial_conditions:

      - user_function: ic_1
        target_name:
          - inner-HEX
          - nearwake-HEX
          - farfield-PYRAMID
          - farfield-TETRA
          - farfield-HEX
        user_function_name:
         velocity: wind_energy_power_law
        user_function_parameters:
          velocity:
            - 2
            - -8.2
            - 8.2
            - 0.12
            - 10.0
            - 0.0
            - 0.0
            - 4.0
            - 16.0

      - constant: ic_2
        target_name:
          - inner-HEX
          - nearwake-HEX
          - farfield-PYRAMID
          - farfield-TETRA
          - farfield-HEX
        value:
          pressure: 0
          turbulent_ke: 0.095118
          specific_dissipation_rate: 2266.4
```

### Inflow BC 

```yaml
    - inflow_boundary_condition: bc_inflow
      target_name: inlet
      inflow_user_data:
        turbulent_ke: 0.095118
        specific_dissipation_rate: 2266.4
        user_function_name:
         velocity: wind_energy_power_law
        user_function_parameters:
          velocity:
            - 2
            - -8.2
            - 8.2
            - 0.12
            - 10.0
            - 0.0
            - 0.0
            - 4.0
            - 16.0
```
