### ISSUE TITLE
trouble running wind profile power law in inlet-BC

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#536]
Hello NALU-Team,

I am trying to run a RANS case with inlet condition as the wind power law profile. The yaml snippet is as follows:

```
 - inflow_boundary_condition: bc_inflow
      target_name: west
      inflow_user_data:
        user_function:
          velocity: wind_energy_power_law
        user_function_parameters:
          velocity: [2, -8.2, 8.2, 0.1428, 10.0, 0, 0, 4.0, 16.0]

```

coord_dir_ = 2, this should correspond to z direction.

When I visualize the flow-field in paraview, I see that the velocity at the inlet = 0 (its acting as a wall).
The log and input .yaml file is attached. I have also attached the velocity contour of the domain, highlighting the inlet condition = 0.

![RANS_ABL_channel](https://user-images.githubusercontent.com/14302216/75290676-cf4d3d00-57ee-11ea-9e6d-7fc2e3959975.PNG)
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4252359/abl_simulation.log)
[abl_simulation.txt](https://github.com/Exawind/nalu-wind/files/4252360/abl_simulation.txt)

I am unsure, how the implementation of the BC went wrong. Any suggestions regarding the matter would be very helpful.

**Comment by sayerhs** [comment]
@tchatte3 There is a typo in your input file. The variable is `user_function_name` and not `user_function`. See example in #534

**Comment by sayerhs** [comment]
A couple of other observations:

- Did you mean to use a `z_offset = -8.2m`? If you were modeling terrain, you want that to be `z_offset = 0`.
- You're applying Coriolis force, but power-law profile will not do any kind of correction for Coriolis as a function of height. Hope that is what you intended.

**Comment by tchatte3** [comment]
@sayerhs ..Thank you very much for the quick response...Yes, I realize my mistake now. Regarding Coriolis force and the param related to z_offset, Yes you are right, I was just playing around with the parameter. I do understand it's a basic wind profile with shear, would not incorporate Eckman spiral.

**Comment by sayerhs** [comment]
Let us know if we can go ahead and close this issue now that your problem has been addressed.

**Comment by tchatte3** [comment]
Thanks, @sayerhs, yes this addresses my issue.

**Comment by tchatte3** [comment]
![image](https://user-images.githubusercontent.com/14302216/75366384-a7141b80-588c-11ea-97ff-d5c09dc4bec2.png)

@sayerhs Apologies, I have to reopen this issue, since fixing the typo does not solve the problem. 

Here is my initial condition block: 
```
initial_conditions:
      - constant: ic_1
        target_name: [fluid_part]
        value:
          pressure: 0
          temperature: 300.0
          turbulent_ke: 2.0
          specific_dissipation_rate: 2.0

      - user_function: ic_2
        target_name: [fluid_part]
        user_function_name:
         velocity: wind_energy_power_law
        user_function_parameters:
         velocity: [2, 0.0, 90.0, 0.1428, 8.0, 0, 0, 2.0, 10.0 ]
```

and here is my inlet BC block:
```
- inflow_boundary_condition: bc_inflow
      target_name: west
      inflow_user_data:
        user_function name:
          velocity: wind_energy_power_law
        user_function_parameters:
          velocity: [2, 0.0, 90.0, 0.1428, 8.0, 0, 0, 2.0, 10.0]

```

In the log file:

```
Mass Balance Review:
Density accumulation: 0
Integrated inflow:    0
Integrated open:      -0.03271442259620017
Total mass closure:   -0.03271442259620017
```
 along with the paraview snapshot indicates that the inlet user function is bypassed and its taking the initialized value = 0.0 (inlet treated as wall).

Log and input yaml files attached.
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4257047/abl_simulation.log)
[abl_simulation.txt](https://github.com/Exawind/nalu-wind/files/4257049/abl_simulation.txt)

Any suggestions, why this is occuring?
