### ISSUE TITLE
Issue with Multiple turbines in ADM/ALM model

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#537]
Hi Nalu-Team,

I tried extending the regression test case for NREL5MWActuatorline/NREL5MWActuatorDisk model for one turbine to multiple turbines, but it is giving me segmentation faults. 

This is a very minimal modification to the regression_test example and it works perfectly fine for one turbine. The error occurs only when I am trying to it use multiple turbines.  This was also tested for multiple processors, but the segmentation fault does not go away 

Log files, and stderr files are attached for reference. 

[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4269141/abl_simulation.log)
[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4269142/abl_simulation.yaml.txt)
[user_script.stderr.txt](https://github.com/Exawind/nalu-wind/files/4269143/user_script.stderr.txt)
[user_script.stdout.txt](https://github.com/Exawind/nalu-wind/files/4269144/user_script.stdout.txt)

Best,
Tanmoy

**Comment by psakievich** [comment]
@tchatte3 looking at where you're stdout is terminating it looks like this is failing in OpenFAST (potentially in servodyn). Does this case work for you with one turbine?  It could be that your library for servodyn is a) not compiled or b) is not being used by the second turbine.

I also see that you're sha from the log file looks like it is from a build in December (d503c4e7).  Could you first try updating builds for OpenFAST and nalu-wind?  When you compile OpenFAST try adding in the compiler flag `-D DBG_OUTS`.  If your building via cmake then add `-DCMAKE_CXX_FLAGS=-D DBG_OUTS` and `-DCMAKE_Fortran_FLAGS=-D DBG_OUTS`.  There is some new functionality in OpenFAST that was added for new features in nalu-wind via #491. 

Also when you compile nalu-wind you can compile with either tests or examples turned on to ensure the servodyn library gets compiled for the nrel5MW case.

**Comment by tchatte3** [comment]
@psakievich , it is indeed failing in OpenFAST, I had some issues with Servodyn in the regression test, so my feature switch for Servodyn, Hydrodyn etc in .fst file has been kept to "0". This case worked for me, for one turbine, but not for two turbines. 

I will try recompiling the Servodyn library, and see if it works.

**Comment by lawrenceccheung** [comment]
@tchatte3 Hi Tanmoy,

I think I'm able to replicate your problem on a very recent nalu-wind build with a very similar (but not exactly the same) setup.  For the me, the problem is independent of whether Servodyn is active or not.

Can you send us the exact grid/domain dimensions and the processor counts that you're using?  Something like the alm_preprocess.yaml would be perfect.  

If memory allows, can you also try running this case on exactly 2 processors?  I'm looking into whether there's an issue with the processor/turbine assignments.

Thanks,

Lawrence

**Comment by tchatte3** [comment]
@lawrenceccheung Thanks. Here is the preprocess file. I am trying to run it on a very coarse grid with 20 processes.

```
# -*- mode: yaml -*-
#
# Nalu Preprocessing utility
#
# Generate a temperature profile with capping inversion for use with ablNeutralEdge case
#

nalu_abl_mesh:
  output_db: mesh_abl.exo

  spec_type: bounding_box

  fluid_part_name: fluid_part

  vertices:
  - [0.0, 0.0, 0.0]
  - [5000.0, 5000.0, 1000.0]

  mesh_dimensions: [100, 100, 50]
  xmin_boundary_name: west
  xmax_boundary_name: east
  ymin_boundary_name: south
  ymax_boundary_name: north
  zmin_boundary_name: lower
  zmax_boundary_name: upper

```
