### ISSUE TITLE
NALU-wind failing in BELOS solvers for certain mesh stretchin ratio

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#590]
Hi NALU-wind team,

I am running a box type hexahedral mesh, with vertical mesh stretching. For some mesh stretching, the code fails on Belos solvers, while for some it does run without any issues. I am using a RANS wall-model, and stretching the mesh would mean smaller cell-sizes at the wall. However, I see the failure is occurring not because the cell-size at the wall is becoming smaller, but when the ratio of wall-cell size / top-BC cell size becomes larger than some threshold. 
[abl_preprocess.yaml.txt](https://github.com/Exawind/nalu-wind/files/4634922/abl_preprocess.yaml.txt)
[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4634923/abl_simulation.yaml.txt)
[user_script.stderr.txt](https://github.com/Exawind/nalu-wind/files/4634929/user_script.stderr.txt)
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4634934/abl_simulation.log)

Physics-wise, this would not make sense, but 
numerically, I am not sure if the matrix-solver is somehow getting ill-conditioned because of this. 

For the nalu abl-mesh utility, that we have been using, 

```
 vertices:
  - [0.0, 0.0, 0.0]
  - [5000, 4000.0, 1000.0]

  mesh_dimensions: [167,134,100]


# Mesh-spacing for vertically refined mesh: mesh streching #
  x_spacing:
    spacing_type: constant_spacing

  y_spacing:
    spacing_type: constant_spacing

  z_spacing:
    spacing_type: geometric_stretching
    stretching_factor: 1.045

```

Interestingly, if we change the mesh-stretching ~ 1.0075, and the vertical cell-counts to 400 from 100, the case runs. it means the wall-cell size is smaller than the current setting, but the top -cell size/ wall cell-size is now smaller. CFL, changing the preconditioners do not help here.

Any suggestions as to why this is happening. 
nalu log files and stderr files and (preprocess, simulation yaml) file is attached below.

**Comment by sayerhs** [comment]
@tchatte3 Assuming you're running with `master` branch of `nalu-wind`, this looks suspect 

```
    - wall_boundary_condition: bc_bot
      target_name: lower
      wall_user_data:
        velocity: [0,0,0]
        turbulent_ke: 1.0875
#        specific_dissipation_rate: 0.25059
        use_wall_function: yes
```

This BC should be set similar to what is used for the wall boundary in `airfoilRANSEdge` regression test case. Specifically, I'd start with `use_wall_function: no`
