### ISSUE TITLE
reading boundary planes in the ioRealm section

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#610]
Hi Nalu-wind team,

I am trying to run the wind farm (precursor driven) example case (or a variant of it). Step 1 and 2, which is for running the fully-developed precursor steady state and extracting the boundary planes work fine. 

I get stuck in Step 3, where the boundary planes are being read. I already have the boundary planes being extracted properly in Step 2. 

![image](https://user-images.githubusercontent.com/14302216/83896425-259d1680-a722-11ea-8af4-fa7915a8139b.png)

This image shows the boundary plane extracted from stop 2.

[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4737180/abl_simulation.yaml.txt)

[user_script.stderr.txt](https://github.com/Exawind/nalu-wind/files/4737189/user_script.stderr.txt)
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4737190/abl_simulation.log)

It is apparent that the error comes from the following section in the yaml script,

``` 
- name: ioRealm
    mesh: ../Boundary_Extraction/boundaryData/BD/boundary_data.exo
    type: external_field_provider
```
I am a little confused since I use the epu tool to join parallel decomposed files boundary_data.exo.20.** to boundary_data.exo, but it seems the code is still looking for file-systems corresponding to the par-decomposed files. I also find the epu-joined boundary_data.exo is working perfectly (png image attached). Any suggestions as to why this might be happening?

Note: I have used this epu method of joining pardecomposed files before in fluidrealm for restart purposes and it has worked fine.

**Comment by sayerhs** [comment]
@tchatte3 If you are using an `epu`ed Exodus file as your `mesh` file then you need to specify 

```
    automatic_decomposition_type: rcb
``` 

in the realm section for that mesh (`ioRealm` in your case). The code currently is not user-friendly in that sense.

**Comment by tchatte3** [comment]
@sayerhs . I added the automatic_decomposition_type: rcb, however I still get an error during runtime. Its in the transfers section.  I am also trying to use the specific dissipation rate variable, I am not sure I setting it right though.

```
transfers:
- name: west
  type: geometric
  realm_pair: [ioRealm, fluidRealm]
  mesh_part_pair: [west,west]
  objective: external_data
  search_tolerance: 5.0e-4
  transfer_variables:
  - [velocity_bc, velocity]
  - [velocity_bc, velocity_bc]
  - [turbulent_ke_bc, turbulent_ke]
  - [turbulent_ke_bc, tke_bc]
  - [specific_dissipation_rate_bc,specific_dissipation_rate]
  - [specific_dissipation_rate_bc,specific_dissipation_rate_bc]
```
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4737782/abl_simulation.log)
[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4737783/abl_simulation.yaml.txt)

The stderr is as follows

``` IOSS: Input database contains 8-byte integers. Setting Ioss to use 8-byte integers.

IOSS: Using decomposition method 'RCB' for 2,623,319 elements on 100 processors.

IOSS: Using decomposition method 'RCB' for 6,499 elements on 100 processors.
_pmiu_daemon(SIGCHLD): [NID 01803] [c1-1c1s2n3] [Fri Jun  5 14:13:06 2020] PE RANK 97 exit signal Segmentation fault
[NID 01803] 2020-06-05 14:13:06 Apid 129525: initiated application termination
```

Any help on what is possibly causing this?
