### ISSUE TITLE
Restarting from a exo files having a different mesh

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#621]
Hi Nalu-wind team, 

Can restarting of a simulation be done from a file that has a different mesh layout (but same domain size)  that the current simulation from which restart is being called. Does it do a grid-to-grid interpolation, automatically or are there any tools that we need  to invoke for that.

Best,
Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 if the domain extents are the same, you can use nalu _transfers_ to interpolate onto the new mesh. Just run for zero timesteps and save the results at the zeroth timestep. Where zeroth timestep is the timestep you want to interpolate into the new mesh.

**Comment by tchatte3** [comment]
@sayerhs , OK, I see your point. Thanks a lot.

**Comment by sayerhs** [comment]
Yes that's correct

**Comment by tchatte3** [comment]
@sayerhs Thank you

**Comment by tchatte3** [comment]
@sayerhs, I have a quick follow up question related to that. I have a ABL mesh with ``target name: fluid part`` and a wind farm mesh with 
`` target name: [fluid_part,fluid_part.pyramid_5._urpconv,fluid_part.tetrahedron_4._urpconv] ``.

When I am using the transfers class, how do I identify the mesh pair
```
transfers:
- name: west
  type: geometric
  realm_pair: [ioRealm, fluidRealm]
  mesh_part_pair: [?.?]
```

When I look at the source code I see the following lines : 

``// proceed safely
    const YAML::Node meshPartPairName = node["mesh_part_pair"];
    if ( meshPartPairName.size() != 2 )
      throw std::runtime_error("need two mesh part pairs for xfer");
    // resize and set the value
    fromPartNameVec_.resize(1);
    toPartNameVec_.resize(1);
    fromPartNameVec_[0] = meshPartPairName[0].as<std::string>() ;
    toPartNameVec_[0] = meshPartPairName[1].as<std::string>() ;``

So, my question is can my meshes be handled with the transfer objective ``initialization" ? Any help regarding this matter?

Best Regards,

**Comment by sayerhs** [comment]
```
transfers:
- name: west
  type: geometric
  realm_pair: [ioRealm, fluidRealm]
  from_target_name: fluid_realm
  to_target_name: 
    - fluid_part
    - fluid_part.pyramid_5._urpconv
    - fluid_part.tetrahedron_4._urpconv
```

https://github.com/Exawind/nalu-wind/blob/6e37d5759cc6e6c4df14964d53e76342662f5dcf/src/xfer/Transfer.C#L130-L154
