### ISSUE TITLE
not writing probe output file

### ISSUE THREAD

**Issue by petesilk** [Exawind/nalu-wind#657]
I followed data_probes template to add line probe to my *.yaml.  Nalu runs fine to completion, but I do not get an output file with the probe data.

`data_probes:
  output_data_base_name: probes.txt
  output_frequency: 1
  output_format: text
  search_method: stk_octree
  search_tolerance: 1.0e-3
  search_expansion_factor: 2.0

  specifications:
    - name: probe_profile
      from_target_part: interior

      line_of_site_specifications: 
        - name: probe_profile
          number_of_points: 4
          tip_coordinates: [-183.5, -102.7, 3.1]
          tail_coordinates: [-180.8, -103.0, 16.1]

      output_variables:
        - field_name: velocity
          field_size: 3
`

What do I need to add/change to obtain an output text file with my probe data?

**Comment by sayerhs** [comment]
Can you please attach the full input file and the log file (you might have to change the extension to `.txt` so that GitHub will allow file upload). The section you've posted is not formatted correctly to determine if there is some yaml syntax error.

**Comment by petesilk** [comment]
[M0.log](https://github.com/Exawind/nalu-wind/files/4920138/M0.log)
[M0.yaml.txt](https://github.com/Exawind/nalu-wind/files/4920139/M0.yaml.txt)

here is the input file and log files you requested.  thx.

**Comment by lawrenceccheung** [comment]
Hi @petesilk, 

The input looks mostly correct, but there's an issue with the formatting in the input file. The `data_probes` section should be indented one level in, so add 4 spaces (or perhaps 1 tab) for that block, otherwise Nalu-Wind will skip over that section.  Also, the `output_data_base_name` parameter is not needed in the `data_probes` section, but it's not doing any harm there.  

Here's how I would have the `data_probes` section formatted, relative to the `output` section:
```yaml
    output:
      output_data_base_name: output/abl_5km_5km_1km_neutral.exo
#      output_frequency: 500 
      output_frequency: 10 
      output_node_set: no
      output_variables:
       - velocity
       - pressure
       - pressure_force
       - tau_wall
       - turbulent_ke
       - specific_dissipation_rate
       - minimum_distance_to_wall
       - turbulent_viscosity
       - element_courant
       - enthalpy
       - temperature
       - effective_viscosity_u

# ....vvvv...Mast M0 location..vvvvvvvv
    data_probes:
      output_frequency: 1
      output_format: text
      search_method: stk_octree
      search_tolerance: 1.0e-3
      search_expansion_factor: 2.0

      specifications:
        - name: probe_profile
          from_target_part: interior

          line_of_site_specifications: 
            - name: probe_profile
              number_of_points: 4
              tip_coordinates: [-183.5, -102.7, 3.1]
              tail_coordinates: [-180.8, -103.0, 16.1]
            
          output_variables:
            - field_name: velocity
              field_size: 3
# ....^^^^^....M0....^^^^^^^^^^^^^^^
```

You can check in the log file to see if Nalu-Wind picks up the `data_probes` section correctly.  In more recent builds of the code, there should be `DataProbePostProcessing` output in the beginning, after the license section and before the `Realm Options Review` section, like this:
```
   See LICENSE file at https://github.com/exawind/nalu-wind for more details.  
-------------------------------------------------------------------------------

DataProbePostProcessing::load
DataProbePostProcessing::Adding text output format...

Realm Options Review: fluidRealm
===========================
Edge-based scheme will be activated
Nalu will deactivate aura ghosting
```
If you don't see this output, then Nalu-Wind didn't read in any data probes.

Hopefully this helps,

Lawrence
