### ISSUE TITLE
Run with multiple lin_of_site_specifications

### ISSUE THREAD

**Issue by petesilk** [Exawind/nalu-wind#660]
I can successfully run with 1 line probe.  However, I have not been able to add a 2nd line probe.  Here are some of the permutations I have tried.  Also, is it possible to place a probe at a specific point?

      specifications:
        - name: probe_profile
          from_target_part: [Volume_Grid-TETRA, Volume_Grid-WEDGE, Volume_Grid-PYRAMID]

          line_of_site_specifications:
            - name: probeM0
              number_of_points: 4
              tip_coordinates: [-180.8, -103.3, 3.1]
              tail_coordinates: [-180.8, -103.3, 16.1]

          output_variables:
            - field_name: velocity
              field_size: 3

      specifications:
#        - name:probe_profile
        - name:probe_M1
          from_target_part: [Volume_Grid-TETRA, Volume_Grid-WEDGE, Volume_Grid-PYRAMID]

          line_of_site_specifications:
            - name: probe_M1
              number_of_points: 4
              tip_coordinates: [-52.4, -31.0, 0.8]
              tail_coordinates: [-52.4, -31.0, 16.1]

          output_variables:
            - field_name: velocity
              field_size: 3

**Comment by sayerhs** [comment]
@petesilk It appears that you have multiple `specifications` entries... 

```YAML
  specifications:
    - name: probe_profile
      from_target_part: [Volume_Grid-TETRA, Volume_Grid-WEDGE, Volume_Grid-PYRAMID]

      line_of_site_specifications:
        - name: probeM0
          number_of_points: 4
          tip_coordinates: [-180.8, -103.3, 3.1]
          tail_coordinates: [-180.8, -103.3, 16.1]

        - name: probe_M1
          number_of_points: 4
          tip_coordinates: [-52.4, -31.0, 0.8]
          tail_coordinates: [-52.4, -31.0, 16.1]

      output_variables:
        - field_name: velocity
          field_size: 3
```

**Comment by sayerhs** [comment]
I am not sure I understood your second question fully. I assume you want a single probe point?

```
  specifications:
    - name: probe_profile
      from_target_part: [Volume_Grid-TETRA, Volume_Grid-WEDGE, Volume_Grid-PYRAMID]

      line_of_site_specifications:
        - name: probeM0
          number_of_points: 1
          tip_coordinates: [-180.8, -103.3, 3.1]
          tail_coordinates: [-180.8, -103.3, 16.1]

      output_variables:
        - field_name: velocity
          field_size: 3
```

**Comment by lawrenceccheung** [comment]
[*Looks like @sayerhs responded just as I was typing, but let me complete the thought*]
Hi @petesilk,

To add multiple line probes, create multiple entries under the `line_of_site_specifications` section.  So to add both `probeM0` and `probe_M1` to the `data_probes` section, I would have something like this:
```yaml
    data_probes:
      output_frequency: 1
      output_format: text
      search_method: stk_octree
      search_tolerance: 1.0e-3
      search_expansion_factor: 2.0

      specifications:
        - name: probe_profile
          from_target_part: interior

          line_of_site_specifications: 
            - name: probeM0
              number_of_points: 4
              tip_coordinates: [-183.5, -102.7, 3.1]
              tail_coordinates: [-180.8, -103.0, 16.1]
            - name: probe_M1
              number_of_points: 4
              tip_coordinates: [-52.4, -31.0, 0.8]
              tail_coordinates: [-52.4, -31.0, 16.1]           
          output_variables:
            - field_name: velocity
              field_size: 3
```

To do create a single point probe, you can abuse the `line_of_site_specifications` input slightly.  Create an entry with `number_of_points:1`, and it will create a single probe point at the **tail_coordinates** location.

More information on the `data_probes` specification is available here: https://nalu-wind.readthedocs.io/en/latest/source/user/nalu_run/nalu_inp.html#data-probes

Lawrence

**Comment by petesilk** [comment]
With the coding below, I only get output from the first probe?

Thank you

**Comment by lawrenceccheung** [comment]
Oh, I may have made a mistake earlier.  Make sure that the `from_target_part` correctly points to whatever domain elements are in the mesh.  So it might need to look like
```yaml
      from_target_part: [Volume_Grid-TETRA, Volume_Grid-WEDGE, Volume_Grid-PYRAMID]
```
to capture all probes.  I just corrected that in my post above.

Lawrence

**Comment by sayerhs** [comment]
@petesilk Can you please attach your yaml input file again. YAML is sensitive to indentation, and small changes can cause it to interpret the file differently. Attaching the input file would be the best way for us to help debug this.

**Comment by petesilk** [comment]
here is the yaml.
Thanks
[M0M1.yaml.txt](https://github.com/Exawind/nalu-wind/files/4938967/M0M1.yaml.txt)

**Comment by lawrenceccheung** [comment]
Hi @petesilk,

You have the `line_of_site_specifications` keyword repeated twice in the specficiation.  So right now where you have
```yaml
          line_of_site_specifications: 
            - name: probeM0
              number_of_points: 4
              tip_coordinates: [-180.8, -103.3, 3.1]
              tail_coordinates: [-180.8, -103.3, 16.1]
          line_of_site_specifications:
             - name: probe_M1
               number_of_points: 4
               tip_coordinates: [-52.4, -31.0, 0.8]
               tail_coordinates: [-52.4, -31.0, 16.1]
```
it should be:
```yaml
          line_of_site_specifications: 
            - name: probeM0
              number_of_points: 4
              tip_coordinates: [-180.8, -103.3, 3.1]
              tail_coordinates: [-180.8, -103.3, 16.1]
            - name: probe_M1
              number_of_points: 4
              tip_coordinates: [-52.4, -31.0, 0.8]
              tail_coordinates: [-52.4, -31.0, 16.1]
```
Also note that `probeM0` and `probe_M1` are on the same level of indentation.

I think that should correct the problem.

Lawrence
